[project]
name = "learning-jev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "huggingface>=0.0.1",
    "ipykernel>=7.3.0",
    "torch>=2.14.0",
]

[project.scripts]
learning-jev = "learning_jev:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
